export const PATHS = {
  LOGIN: "/login",
  SIGNUP: "/signup",
  DASHBOARD: "/dashboard",
  TRACKING: "/tracking",
  MAP: "/map",
  VEHICLES: "/vehicles",
  TRIPS: "/trips",
  GEOFENCE: "/geofence",
  ALERTS: "/alerts",
  REPORTS: "/reports",
  ANALYTICS: "/analytics",
  FLEET_INTEL: "/fleet-intelligence",
  DEVICES: "/devices",
  LOAD_CELL: "/load-cell",
  LIVE_LOAD: "/live-load",
  USERS: "/users",
  SETTINGS: "/settings",
};
export default PATHS;
